### ISSUE TITLE
Add titles in insights

### ISSUE THREAD

**Issue by danana** [danciotu/deepstash#11]
un insight are titlu, poza si continut
titlul si poza pot lipsi
continutul e obligatoriu

Daca exista, sa afisam si titlurile.
cc @hpaul @mateioprea - cereti de la Paul G. reguli pentru titles (sunt cateva sugestii aici vad: https://invis.io/FRPOJJ0G6BY )

**Comment by danana** [comment]
Reguli aici: https://invis.io/FCPOKRRXGU9

**Comment by hpaul** [comment]
Done.
